gesdinet_jwt_refresh_token:
    refresh_token_class: App\User\Infrastructure\RefreshToken
    ttl: 2592000  # 30 days
    ttl_update: true
    token_parameter_name: refresh_token
    return_expiration: true
    single_use: true
