framework:
    router:
        default_uri: 'https://programel.com'

when@dev:
    framework:
        router:
            default_uri: 'https://programel.local'

when@prod:
    framework:
        router:
            strict_requirements: null
