<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260513220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add e-queue monitor and Telegram account tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE equeue_snapshot (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                status VARCHAR(32) NOT NULL,
                http_status INT NOT NULL,
                payload JSON NOT NULL,
                slot_count INT NOT NULL,
                parser_version VARCHAR(32) NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_equeue_snapshot_fetched_at ON equeue_snapshot (fetched_at)');
        $this->addSql("COMMENT ON COLUMN equeue_snapshot.fetched_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql(<<<'SQL'
            CREATE TABLE equeue_watch (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                service_code VARCHAR(128) NOT NULL,
                service_label VARCHAR(255) DEFAULT NULL,
                date_from DATE NOT NULL,
                date_to DATE NOT NULL,
                active BOOLEAN NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_equeue_watch_user_active ON equeue_watch (user_id, active)');
        $this->addSql("COMMENT ON COLUMN equeue_watch.date_from IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN equeue_watch.date_to IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN equeue_watch.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN equeue_watch.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql(<<<'SQL'
            ALTER TABLE equeue_watch
                ADD CONSTRAINT fk_equeue_watch_user
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE equeue_notification (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                watch_id INT NOT NULL,
                slot_signature VARCHAR(64) NOT NULL,
                sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                telegram_message_id BIGINT DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_equeue_notification_watch_slot ON equeue_notification (watch_id, slot_signature)');
        $this->addSql("COMMENT ON COLUMN equeue_notification.sent_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql(<<<'SQL'
            ALTER TABLE equeue_notification
                ADD CONSTRAINT fk_equeue_notification_watch
                FOREIGN KEY (watch_id) REFERENCES equeue_watch (id) ON DELETE CASCADE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE telegram_account (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                chat_id BIGINT DEFAULT NULL,
                connect_token VARCHAR(64) DEFAULT NULL,
                token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                connected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_telegram_account_user ON telegram_account (user_id)');
        $this->addSql('CREATE INDEX idx_telegram_account_connect_token ON telegram_account (connect_token)');
        $this->addSql("COMMENT ON COLUMN telegram_account.token_expires_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN telegram_account.connected_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql(<<<'SQL'
            ALTER TABLE telegram_account
                ADD CONSTRAINT fk_telegram_account_user
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS equeue_notification');
        $this->addSql('DROP TABLE IF EXISTS equeue_watch');
        $this->addSql('DROP TABLE IF EXISTS equeue_snapshot');
        $this->addSql('DROP TABLE IF EXISTS telegram_account');
    }
}
