<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514171613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equeue_raw_html (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, alert_present BOOLEAN NOT NULL, html_body TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_equeue_raw_html_fetched_at ON equeue_raw_html (fetched_at)');
        $this->addSql('COMMENT ON COLUMN equeue_notification.sent_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN equeue_snapshot.fetched_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.date_from IS \'\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.date_to IS \'\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN telegram_account.token_expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN telegram_account.connected_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_telegram_account_user RENAME TO UNIQ_26703752A76ED395');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE equeue_raw_html');
        $this->addSql('COMMENT ON COLUMN equeue_notification.sent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equeue_snapshot.fetched_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.date_from IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.date_to IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equeue_watch.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN telegram_account.token_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN telegram_account.connected_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_26703752a76ed395 RENAME TO uniq_telegram_account_user');
    }
}
