<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514171613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add equeue_raw_html table with fetched_at index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE equeue_raw_html (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, alert_present BOOLEAN NOT NULL, html_body TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_equeue_raw_html_fetched_at ON equeue_raw_html (fetched_at)');
        $this->addSql('COMMENT ON COLUMN equeue_raw_html.fetched_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE equeue_raw_html');
    }
}
