<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519062928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_center.slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slots JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_document_center_slot_fetched_at ON document_center.slot (fetched_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE document_center.slot');
    }
}
