controllers:
    resource:
        path: ../src/
        namespace: App
    type: attribute

api_login:
    path: /api/v1/auth/login
    methods: [POST]

api_refresh_token:
    path: /api/v1/auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
