services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\Fake\:
        resource: '../tests/Behat/Fake/*'

    App\DocumentCenter\Infrastructure\Fetcher\DocumentCenterFetcherInterface: '@App\Tests\Behat\Fake\FakeDocumentCenterFetcher'

    App\DocumentCenter\Application\PollDocumentCenter\PollDocumentCenterHandler:
        arguments:
            $fetcher: '@App\Tests\Behat\Fake\FakeDocumentCenterFetcher'
            $slotScraper: '@App\Tests\Behat\Fake\FakeSlotScraper'

    Symfony\Component\Messenger\Transport\InMemory\InMemoryTransport:
        alias: messenger.transport.async
        public: true
